[package]
name = "meread"
version = "0.1.3"
description = "preview github flavored markdown locally"
repository = "https://github.com/sermuns/meread"
license = "WTFPL"
edition = "2024"
keywords = ["readme", "markdown", "preview", "server"]
categories = ["command-line-utilities", "web-programming::http-server"]

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
axum = "0.8"
tower-livereload = "0.9.6"
markdown = "1.0.0"
tower-http = { version = "0.6.6", features = ["fs"] }
notify = "8.1.0"
clap = { version = "4.5.40", features = ["derive"] }
askama = "0.14.0"
axum-embed = "0.1.0"
rust-embed = "8.7.2"
open = "5.3.2"

[profile.release]
lto = true
codegen-units = 1
strip = true

[profile.dev]
debug = 0
