name: Publish README on GitHub pages
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/site.yml
      - README.md
      - assets/**
      - media/**

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write # to use actions/deploy-pages
      pages: write # to push to a github pages site
    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2

      - run: cargo run -- -e public

      - run: cp -r media public/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - id: deployment
        uses: actions/deploy-pages@v4
